### PR TITLE
Add new functions for arrutil #44 

### PR DESCRIPTION
**Pull request by ah-its-andy**
#44 

function | comment | unit tests | benchmark 
----|----|----|----
arrutil.TwowaySearch | Find specialized element in a slice forward and backward in the same time, should be more quicker. | yes | no 
arrutil.Excepts | Produces the set difference of two slice according to a comparer function | yes | no
arrutil.Intersects | Produces the intersect  of two slice according to a comparer function | yes | no
arrutil.Union | Produces the set union of two slice  according to a comparer function | yes | no
arrutil.Find | Produces the struct/value of a slice according to a predicate function | yes | no
arrutil.FindOrDefault | Produce the struct/value f a slice to a predicate function, produce default value when predicate function not match | yes | no
arrutil.TakeWhile | Produce the set of a slice according to a predicate function, produce empty slice when predicate function not match | yes | no
arrutil.ExceptWhile | Produce the set of a slice except with a predicate function, produce original slice when predicate function not match | yes | no

### CODE REVIEW

**Comment by inhere** [comment]
hi @ah-its-andy 👍  Great

----

needs some small tweaks:

- add comment to function

**Comment by ah-its-andy** [comment]
> hi @ah-its-andy 👍 Great
> 
> needs some small tweaks:
> 
> * add comment to function

Done.

**Comment by ah-its-andy** [comment]
seems something went wrong. @inhere

**Comment by inhere** [comment]
Merged, thanks @ah-its-andy 👍

**Pull request merged**
